--- #YAML:1.0
name:               Dancer-Plugin-LibraryThing
version:            0.0001
abstract:           Plugin for LibraryThing APIs.
author:
    - Stefan Hornburg (Racke) <racke@linuxia.de>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Test::More:           0
    WWW::LibraryThing::Covers:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
